# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xinlireading', '0002_auto_20160528_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xinlireading.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xinlireading.Person')),
                ('reading_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xinlireading.ReadingGroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmembership',
            name='person',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
        migrations.AddField(
            model_name='readinggroup',
            name='members',
            field=models.ManyToManyField(through='xinlireading.ReadingGroupMembership', to='xinlireading.Person'),
        ),
    ]
