# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xinlireading', '0003_auto_20160528_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
        migrations.AddField(
            model_name='note',
            name='reading_group_membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xinlireading.ReadingGroupMembership'),
            preserve_default=False,
        ),
    ]
