# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xinlireading', '0004_auto_20160528_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='reader_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='note',
            name='reading_group_membership',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='xinlireading.ReadingGroupMembership'),
        ),
    ]
