# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 02:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xinlireading', '0005_auto_20160528_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='reading_group_membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xinlireading.ReadingGroupMembership'),
        ),
    ]
