# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xinlireading', '0006_auto_20160528_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='xinlireading.Book'),
        ),
    ]
